name: Documentation CI
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write

jobs:
  docs:
    uses: kordlib/.teamcity/.github/workflows/wiki.yml@main
    with:
      build-dokka: true
      path: docs/c
      product: C
      algolia-index: codegen_kt_wiki
      version: main-SNAPSHOT
      algolia-token: ${{ secrets.ALGOLIA_KEY }}
